# Generated by Django 4.2.5 on 2023-10-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=1)),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
                ('max_hit_points', models.PositiveIntegerField(default=10)),
                ('current_hit_points', models.PositiveIntegerField(default=10)),
                ('alignment', models.CharField(max_length=20)),
                ('background', models.CharField(max_length=50)),
                ('personality_traits', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_character.characterclass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_character.race')),
            ],
        ),
    ]
