# Generated by Django 4.2.5 on 2023-11-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_character', '0004_alter_character_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_character.alignment'),
        ),
    ]
