# Generated by Django 4.2.5 on 2023-10-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fediverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('api_base_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MastodonUserProfile',
        ),
    ]
