# Generated by Django 4.2.5 on 2023-10-30 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fediverse', '0002_mastodonuser_delete_mastodonuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
